# Generated by Django 3.0.7 on 2020-06-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200614_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormData',
            new_name='Form',
        ),
    ]
